/*
 * Project #3
 * Programmer: Mattea Jones
 * Due: 4/12/18
 * Description: Rock paper scissors game. Takes user input and compares it to a
 * number randomly generated by the computer.
 */

package project3;
import java.util.Scanner;

public class Project3 {
    
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in); 
        
        int rnd = 0; //keep track of rounds
        //keep track of wins/loses
        int compWin = 0;
        int userWin = 0;
        int draw = 0;
        
        
        System.out.print("Enter scissors (0), rock (1), paper (2) or exit (-1): ");
        int userChoice = input.nextInt();
        while (userChoice > -1) { //exit if negative / go while not negative
            int rand = (int) (Math.random() * 3); // random number 0, 1 or 2
            if(userChoice > -1 && userChoice < 3) {//choices if rock/paper/scissors 
                String userStr = intToStr(userChoice); //call a function to print a word instead of a number
                String compStr =intToStr(rand);
                if (userChoice == rand) {//if the choices are the same
                    System.out.println("The computer is " + compStr + ". You are " + userStr + " too. It is a draw.");
                    draw++; //store draw
                }
                //if greater than rand by 1 or 0 and 2
                else if ((userChoice > rand && (userChoice - rand) == 1) || (userChoice == 0 && rand == 2)) {
                    System.out.println("The computer is " + compStr + ". You are " + userStr + ". You won.");
                    userWin++; //store player wins
                }
                else {
                    System.out.println("The computer is " + compStr + ". You are "+ userStr + ". You lose.");
                    compWin++; // store computer win
                }
            }
            else {//else print wrong input
                System.out.println(userChoice + " is not a valid guess, please try again.");
                rnd--; //counterbalances round counter
            }
            rnd++; //add a round
            System.out.print("Enter scissors (0), rock (1), paper (2) or exit (-1): ");
            userChoice = input.nextInt();
        }
        //print score list
        System.out.println("\nProgram Results: \n--------------- \nRounds played: " + rnd + 
                "\nPlayer wins: " + userWin + "\nComputer wins: " + compWin + "\nDraws: " + draw);
    }
    
    public static String intToStr(int num){
        String str;
        switch (num){
            case 0: str = "scissors"; break;
            case 1: str = "rock"; break;
            case 2: str = "paper"; break;
            default: str = "oops";
        }
        return str;
    }

}
